Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2018-09, with the labels that each got.

#281 Handle missing service catalog endpoint
  app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb
Labels: bug

#282 Move ManagerRefresh to InventoryRefresh
  app/models/manageiq/providers/kubernetes/container_manager/inventory_collector_mixin.rb
  app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb
  app/models/manageiq/providers/kubernetes/container_manager/refresher_mixin.rb
  spec/models/manageiq/providers/kubernetes/container_manager/targeted_refresh/targeted_refresh_spec.rb
Labels: refactoring

#283 Fix watches when using service catalog endpoint
  app/models/manageiq/providers/kubernetes/inventory/collector/watches.rb
Labels: bug, inventory

#289 Fix MetricsCapture and Refresher specs failing due to a missing zone
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_client_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_legacy_capture_context_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/rollup_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/targeted_refresh/targeted_refresh_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
Labels: test

#288 Discover API endpoint in kubernetes_connection
  app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
  app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb
  spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
Labels: enhancement, inventory

#291 Handle deleted entities
  app/models/manageiq/providers/kubernetes/container_manager/streaming_refresh_mixin.rb
  app/models/manageiq/providers/kubernetes/inventory/collector/watches.rb
  app/models/manageiq/providers/kubernetes/inventory/parser/watches.rb
Labels: enhancement

#292 [Changelog] Update for Sprint 95
  CHANGELOG.md
Labels: documentation

#293 [Changelog] Update for Hammer Beta-1 release
  CHANGELOG.md
Labels: documentation
