Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2018-06, with the labels that each got.

#254 Bump to ruby 2.4.4 for great justice
  .travis.yml
Labels: gaprindashvili/no, test

#258 [Changelog] Update for Gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#259 Kubevirt should report its own status
  app/models/manageiq/providers/kubernetes/virtualization_manager_mixin.rb
Labels: bug

#260 Kubevirt should reports its auth status
  app/models/manageiq/providers/kubernetes/virtualization_manager_mixin.rb
Labels: bug

#262 [Changelog] Update for Sprint 88
  CHANGELOG.md
Labels: documentation

#264 Set EmsEvent ems_ref to event's uid, to avoid same-second collision
  app/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin.rb
  app/models/manageiq/providers/kubernetes/container_manager/event_parser_mixin.rb
  spec/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin_spec.rb
Labels: bug, events, gaprindashvili/yes
