Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2018-11, with the labels that each got.

#298 [HAMMER] Add translations for hammer
  locale/es/ManageIQ_Providers_Kubernetes.po
  locale/fr/ManageIQ_Providers_Kubernetes.po
  locale/ja/ManageIQ_Providers_Kubernetes.po
  locale/pt_BR/ManageIQ_Providers_Kubernetes.po
  locale/zh_CN/ManageIQ_Providers_Kubernetes.po
Labels: internationalization

#302 Fix rollup specs for project derived mem/cpu
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/rollup_spec.rb
Labels: test

#299 Override Job#process_cancel to send :cancel signal
  app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb
Labels: bug

#304 Different way to check for scan job's complete state.
  app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb
  spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
Labels: bug, hammer/yes

#307 [Changelog] Update for Sprint 99
  CHANGELOG.md
Labels: documentation

#309 Refactor the event catcher filtered? method
  app/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin.rb
  spec/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin_spec.rb
Labels: bug

#306 [GAPRINDASHVILI] Use working-set instead of usage for memory
  app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_spec.rb
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_container_metrics.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_container_timespan.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_m_endpoint.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_node_metrics.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_node_timespan.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_pod_metrics.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_pod_timespan.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_refresh.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_status.yml
Labels: blocker, bug

#310 [HAMMER] [Changelog] Update for Hammer RC2
  CHANGELOG.md
Labels: documentation
