Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2018-04, with the labels that each got.

#246 Change saver_strategy value to String
  app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb
  config/settings.yml
  spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/targeted_refresh/targeted_refresh_spec.rb
Labels: bug, gaprindashvili/yes

#244 Propagate userid through to create a scanning job with current userid
  app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
  spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#247 [Changelog] Update for Sprint 83
  CHANGELOG.md
Labels: documentation

#249 Add a config option to force legacy hawkular collector
  app/models/manageiq/providers/kubernetes/container_manager/metrics_capture.rb
  config/settings.yml
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture_spec.rb
Labels: blocker, bug, gaprindashvili/yes, metrics

#250 Bump to ruby 2.3.6
  .travis.yml
Labels: test

#251 Add .yamllint from provider generator
  .yamllint
Labels: test

#252 [Changelog] Update for Sprint 84
  CHANGELOG.md
Labels: documentation
