Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2018-08, with the labels that each got.

#272 Allow proper targeted refresh
  app/models/manageiq/providers/kubernetes/inventory/persister/definitions/container_collections.rb
  app/models/manageiq/providers/kubernetes/inventory/persister/target_collection.rb
Labels: enhancement, gaprindashvili/no, inventory

#271 Streaming refresh for kubernetes using watches
  app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/kubernetes/container_manager/streaming_refresh_mixin.rb
  app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
  app/models/manageiq/providers/kubernetes/inventory.rb
  app/models/manageiq/providers/kubernetes/inventory/collector.rb
  app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb
  app/models/manageiq/providers/kubernetes/inventory/collector/watches.rb
  app/models/manageiq/providers/kubernetes/inventory/parser.rb
  app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb
  config/settings.yml
Labels: enhancement

#274 Move streaming_refresh_enabled method
  app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
Labels: gaprindashvili/no, refactoring

#277 Add plugin display name
  lib/manageiq/providers/kubernetes/engine.rb
Labels: enhancement, gaprindashvili/no

#275 Restart stale watch threads where they left off
  app/models/manageiq/providers/kubernetes/container_manager/streaming_refresh_mixin.rb
Labels: bug, inventory

#278 Finish the watch stream connection when exiting
  app/models/manageiq/providers/kubernetes/container_manager/streaming_refresh_mixin.rb
Labels: enhancement, inventory

#276 Refresh service catalog entities
  app/models/manageiq/providers/kubernetes/container_manager/service_offering.rb
  app/models/manageiq/providers/kubernetes/container_manager/service_parameters_set.rb
  app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
  app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb
  app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb
  app/models/manageiq/providers/kubernetes/inventory/persister/definitions/container_collections.rb
Labels: enhancement, inventory

#279 Move Inventory to ManageIQ::Providers
  app/models/manageiq/providers/kubernetes/inventory.rb
  app/models/manageiq/providers/kubernetes/inventory/collector.rb
  app/models/manageiq/providers/kubernetes/inventory/parser.rb
  app/models/manageiq/providers/kubernetes/inventory/persister.rb
Labels: refactoring

#280 [Changelog] Update for Sprint 93
  CHANGELOG.md
Labels: documentation
