Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2018-03, with the labels that each got.

#237 [Changelog] Update for Sprint 80
  CHANGELOG.md
Labels: documentation

#240 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-2
  CHANGELOG.md
Labels: documentation

#198 Keep quota history by archiving
  app/models/manageiq/providers/kubernetes/container_manager/inventory_collections.rb
  app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb
  manageiq-providers-kubernetes.gemspec
  spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
Labels: enhancement, gaprindashvili/yes

#241 [Changelog] Add Gaprindashvili-2
  CHANGELOG.md
Labels: documentation

#232 Bump kubeclient to >=2.5.2 <2.6
  manageiq-providers-kubernetes.gemspec
Labels: bug, gaprindashvili/yes

#242 Avoid refresh crash on Service without matchin Endpoints
  app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb
  spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/refresher_after_deletions.txt
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/refresher_after_deletions.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/refresher_before_deletions.txt
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/refresher_before_deletions.yml
Labels: bug, gaprindashvili/yes, inventory

#243 [Changelog] Update for Sprint 82
  CHANGELOG.md
Labels: documentation
