Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2018-02, with the labels that each got.

#235 Test :batch strategy with and without :use_ar_object.
  spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/targeted_refresh/targeted_refresh_spec.rb
Labels: gaprindashvili/no, test

#233 abort container ssa if can't fetch metadata
  app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb
  spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
Labels: bug, smart state

#229 [Changelog] Update for Sprint 78 and Gaprindashvili-1 release
  CHANGELOG.md
Labels: documentation

#236 [Changelog] Update for Sprint 79
  CHANGELOG.md
Labels: documentation
