Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2018-05, with the labels that each got.

#253 [GAPRINDASHVILI] [Changelog] Update for gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#257 Default to force Hawkular legacy metrics collector
  config/settings.yml
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture_spec.rb
Labels: bug, metrics

#255 mapping.tag is a category Tag, calling .category is ill-defined
  spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
Labels: technical debt, test
