Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2019-11, with the labels that each got.

#346 Remove unused InventoryCollectorWorker
  app/models/manageiq/providers/kubernetes/container_manager.rb
  app/models/manageiq/providers/kubernetes/container_manager/inventory_collector_mixin.rb
  app/models/manageiq/providers/kubernetes/container_manager/inventory_collector_worker.rb
  app/models/manageiq/providers/kubernetes/container_manager/inventory_collector_worker/runner.rb
  config/settings.yml
Labels: cleanup

#349 Add codeowners
  .github/CODEOWNERS
Labels: documentation

#350 Rely on the default implementation of .ems_class
  app/models/manageiq/providers/kubernetes/container_manager/event_catcher.rb
  app/models/manageiq/providers/kubernetes/container_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/kubernetes/container_manager/refresh_worker.rb
  app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher.rb
Labels: refactoring
