Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2019-01, with the labels that each got.

#319 MonitoringManager spec: update to explicitly start from unvalidated auth
  spec/models/manageiq/providers/kubernetes/monitoring_manager_spec.rb
Labels: test

#321 Remove duplicated persister shared_options
  app/models/manageiq/providers/kubernetes/inventory/persister/container_manager.rb
Labels: refactoring

#322 Change FactoryGirl to FactoryBot
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/kubernetes/container_manager/container_group_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/container_image_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/container_node_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/container_project_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/container_route_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_client_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_legacy_capture_context_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/rollup_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/targeted_refresh/targeted_refresh_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
  spec/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin_spec.rb
  spec/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/stream_spec.rb
  spec/models/manageiq/providers/kubernetes/monitoring_manager_spec.rb
Labels: gaprindashvili/no, hammer/no, test

#323 [Changelog] Update for Hammer-1
  CHANGELOG.md
Labels: documentation
