Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2020-07, with the labels that each got.

#386 Fix node network metrics with ens.* interfaces
  app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context.rb
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_node_metrics.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_node_timespan.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_pod_metrics.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_pod_timespan.yml
Labels: bug, jansa/yes?, metrics

#384 bump more core extension dependency
  manageiq-providers-kubernetes.gemspec
Labels: dependencies

#389 PERF_ROLLUP_CHILDREN should be an Array
  app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
Labels: cleanup

#390 Add APP_PATH to allow using Rails directly
  bin/rails
Labels: developer, enhancement
