Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2020-09, with the labels that each got.

#395 Bump hawkular-client to 5.0.0
  app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_client_mixin.rb
  manageiq-providers-kubernetes.gemspec
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_container_metrics.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_container_timespan.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_m_endpoint.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_node_metrics.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_node_timespan.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_pod_metrics.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_pod_timespan.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_refresh.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_capture_context_status.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_client_gauges_query.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_client_get_data.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_client_try_connect.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_legacy_capture_context_container_metrics.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_legacy_capture_context_container_timespan.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_legacy_capture_context_node_metrics.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_legacy_capture_context_node_timespan.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_legacy_capture_context_pod_metrics.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_legacy_capture_context_pod_timespan.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_legacy_capture_context_refresh.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/hawkular_legacy_capture_context_status.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_container_metrics.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_container_timespan.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_node_metrics.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_node_timespan.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_pod_metrics.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_pod_timespan.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_capture_context_refresh.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_fail_connect.yml
  spec/vcr_cassettes/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_try_connect.yml
Labels: dependencies

#396 Fix bug where settings changes are not reflected in the list
  app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
  spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
Labels: bug

#399 Use the tag_mapper from the core Persister
  app/models/manageiq/providers/kubernetes/inventory/persister.rb
  app/models/manageiq/providers/kubernetes/inventory/persister/container_manager.rb
Labels: refactoring

#400 Rename ContainerLabelTagMapping
  spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
Labels: refactoring

#401 Make the credentials required in the provider DDF
  app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
Labels: bug

#402 Prefer ManageIQ::Password over legacy MiqPassword constant
  app/models/manageiq/providers/kubernetes/container_manager_mixin.rb
Labels: enhancement
