Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2020-03, with the labels that each got.

#355 Fix warning and strict partial failure
  spec/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/scanning/job_spec.rb
Labels: refactoring, test

#357 [IVANCHUK] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#358 [JANSA] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#359 Use be_within to fix rollup_spec sporadic failure
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture/rollup_spec.rb
Labels: bug/sporadic test failure, test

#360 Cleanup watches refresh from topology
  app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/kubernetes/container_manager/streaming_refresh_mixin.rb
  app/models/manageiq/providers/kubernetes/inventory/collector.rb
  app/models/manageiq/providers/kubernetes/inventory/collector/watches.rb
  app/models/manageiq/providers/kubernetes/inventory/parser/watches.rb
Labels: cleanup

#361 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#363 Cleanup unused target_collection
  app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb
  app/models/manageiq/providers/kubernetes/container_manager/refresher.rb
  app/models/manageiq/providers/kubernetes/container_manager/refresher_mixin.rb
  app/models/manageiq/providers/kubernetes/container_manager/target_collection_mixin.rb
  app/models/manageiq/providers/kubernetes/inventory/collector.rb
  app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb
  app/models/manageiq/providers/kubernetes/inventory/collector/target_collection.rb
  app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb
  app/models/manageiq/providers/kubernetes/inventory/persister.rb
  app/models/manageiq/providers/kubernetes/inventory/persister/target_collection.rb
  spec/models/manageiq/providers/kubernetes/container_manager/targeted_refresh/targeted_refresh_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/targeted_refresh/watch_pod_stress_4.json
  spec/models/manageiq/providers/kubernetes/container_manager/targeted_refresh/watch_pod_stress_5.json
Labels: cleanup

#362 Refactor graph refresh to match current standards
  app/models/manageiq/providers/kubernetes/container_manager.rb
  app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb
  app/models/manageiq/providers/kubernetes/container_manager/refresher.rb
  app/models/manageiq/providers/kubernetes/container_manager/refresher_mixin.rb
  app/models/manageiq/providers/kubernetes/inventory/collector.rb
  app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb
  app/models/manageiq/providers/kubernetes/inventory/parser.rb
  app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb
  spec/models/manageiq/providers/kubernetes/container_manager/refresh_mixin_spec.rb
  spec/models/manageiq/providers/kubernetes/inventory/parser/container_manager_spec.rb
Labels: refactoring
