Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2020-10, with the labels that each got.

#388 Fix "private method 'watch' called for WatchThread"
  app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb
Labels: bug

#403 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#379 Switch to manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-providers-kubernetes.gemspec
Labels: unmergeable

#404 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer

#405 [KASPAROV] Test with ruby 2.6.6 on Kasparov
  .travis.yml
Labels: test
