Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2020-05, with the labels that each got.

#372 Add targeted refresh for services and endpoints
  app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/kubernetes/inventory/collector.rb
  app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb
  app/models/manageiq/providers/kubernetes/inventory/collector/watch_notice.rb
  app/models/manageiq/providers/kubernetes/inventory/parser/watch_notice.rb
  spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
  spec/models/manageiq/providers/kubernetes/inventory/collector/watch_notice_spec.rb
Labels: enhancement, jansa/yes?

#375 Add parser methods for entity manager_refs
  app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb
  app/models/manageiq/providers/kubernetes/inventory/parser/watch_notice.rb
  app/models/manageiq/providers/kubernetes/inventory/persister.rb
Labels: jansa/yes?

#374 [JANSA] Use watches for targeted refresh
  app/models/manageiq/providers/kubernetes/container_manager/refresh_worker.rb
  app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb
  app/models/manageiq/providers/kubernetes/inventory/collector.rb
  app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb
  app/models/manageiq/providers/kubernetes/inventory/collector/watch_notice.rb
  app/models/manageiq/providers/kubernetes/inventory/parser.rb
  app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb
  app/models/manageiq/providers/kubernetes/inventory/parser/watch_notice.rb
  app/models/manageiq/providers/kubernetes/inventory/persister.rb
  app/models/manageiq/providers/kubernetes/inventory/persister/watch_notice.rb
  spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/endpoint.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/limit_range.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/namespace.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/new_limit_range.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/new_namespace.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/new_node.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/new_persistent_volume.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/new_persistent_volume_claim.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/new_pod.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/new_replication_controller.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/new_resource_quota.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/new_service.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/node.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/persistent_volume.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/pod.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/replication_controller.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/resource_quota.yml
  spec/models/manageiq/providers/kubernetes/container_manager/watches_data/service.yml
  spec/models/manageiq/providers/kubernetes/inventory/parser/container_manager_spec.rb
Labels: enhancement, performance

#376 Update kubeclient to v4.6
  manageiq-providers-kubernetes.gemspec
Labels: dependencies

#377 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#378 Removing deprecated Gemnasium badge
  README.md
Labels: developer
