Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2021-03, with the labels that each got.

#428 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#421 Add systemd unit files for workers
  build/systemd_units/manageiq-providers-kubernetes_container_manager_event_catcher.target
  build/systemd_units/manageiq-providers-kubernetes_container_manager_event_catcher@.service
  build/systemd_units/manageiq-providers-kubernetes_container_manager_metrics_collector.target
  build/systemd_units/manageiq-providers-kubernetes_container_manager_metrics_collector@.service
  build/systemd_units/manageiq-providers-kubernetes_container_manager_refresh.target
  build/systemd_units/manageiq-providers-kubernetes_container_manager_refresh@.service
  build/systemd_units/manageiq-providers-kubernetes_monitoring_manager_event_catcher.target
  build/systemd_units/manageiq-providers-kubernetes_monitoring_manager_event_catcher@.service
Labels: technical debt

#431 Only collect metrics if the metrics endpoint has valid authentication
  app/models/manageiq/providers/kubernetes/container_manager/metrics_capture.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture_spec.rb
Labels: bug, performance
