Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2021-05, with the labels that each got.

#433 Subclassed provider classes should mark the parent as a leaf class
  app/models/manageiq/providers/kubernetes/container_manager.rb
  app/models/manageiq/providers/kubernetes/container_manager/container.rb
  app/models/manageiq/providers/kubernetes/container_manager/container_group.rb
  app/models/manageiq/providers/kubernetes/container_manager/container_node.rb
  app/models/manageiq/providers/kubernetes/container_manager/container_template.rb
Labels: refactoring

#434 Handle a null byte in Node systemUUID
  app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb
  spec/models/manageiq/providers/kubernetes/inventory/parser/container_manager_spec.rb
Labels: bug

#435 Add supports :metrics and check for metrics endpoint
  app/models/manageiq/providers/kubernetes/container_manager.rb
Labels: enhancement

#436 Strip any null bytes from systemUUID in node hash
  app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb
  spec/models/manageiq/providers/kubernetes/inventory/parser/container_manager_spec.rb
Labels: bug, lasker/yes?
