Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2021-02, with the labels that each got.

#422 Fix instance connect options for username/password
  app/models/manageiq/providers/kubernetes/container_manager.rb
Labels: bug

#423 Move Inventory WatchNotice under ContainerManager
  app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/kubernetes/inventory/collector.rb
  app/models/manageiq/providers/kubernetes/inventory/collector/container_manager.rb
  app/models/manageiq/providers/kubernetes/inventory/collector/container_manager/watch_notice.rb
  app/models/manageiq/providers/kubernetes/inventory/parser.rb
  app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb
  app/models/manageiq/providers/kubernetes/inventory/parser/container_manager/watch_notice.rb
  app/models/manageiq/providers/kubernetes/inventory/persister.rb
  app/models/manageiq/providers/kubernetes/inventory/persister/container_manager.rb
  app/models/manageiq/providers/kubernetes/inventory/persister/container_manager/watch_notice.rb
  app/models/manageiq/providers/kubernetes/inventory/persister/watch_notice.rb
  spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
  spec/models/manageiq/providers/kubernetes/inventory/collector/container_manager/watch_notice_spec.rb
Labels: refactoring

#424 Skip refresh if no notices left after filtering
  app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb
Labels: refactoring

#425 Convert `supports_#{op}?` to `supports?(op)`
  app/models/manageiq/providers/kubernetes/container_manager.rb
Labels: refactoring

#426 Adjust empty/initial values for select fields in DDF schemas
  app/models/manageiq/providers/kubernetes/container_manager.rb
Labels: enhancement
