Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2022-11, with the labels that each got.

#475 Use postgresql:13 image for ci
  .github/workflows/ci.yaml
Labels: test

#476 Fix the MetricsCollectorWorker running with invalid creds
  app/models/manageiq/providers/kubernetes/container_manager/metrics_collector_worker.rb
Labels: bug

#477 Fix blank metrics auth record being created
  app/models/manageiq/providers/kubernetes/container_manager.rb
  spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
Labels: bug, oparin/yes?
