Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2023-06, with the labels that each got.

#493 Check metrics authentication validity before perf_capture_queue
  app/models/manageiq/providers/kubernetes/container_manager/metrics_capture.rb
  spec/factories/container_group.rb
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/kubernetes/container_manager/metrics_capture_spec.rb
Labels: bug, metrics

#495 Revert "Merge pull request #492 from DavidResende0/remove-validation-dependecies"
  app/models/manageiq/providers/kubernetes/container_manager.rb
Labels: petrosian/yes

#497 Convert the duration to a float
  app/models/manageiq/providers/kubernetes/container_manager/refresh_worker/watch_thread.rb
Labels: bug, ruby3, petrosian/yes?
