Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2024-07, with the labels that each got.

#531 Provide backward compatible way to globally set permitted classes
  spec/models/manageiq/providers/kubernetes/container_manager/scanning/job/dispatcher_spec.rb
Labels: enhancement, rails7

#530 Add annotations to container summary pages
  app/models/manageiq/providers/kubernetes/inventory/parser/container_manager.rb
  app/models/manageiq/providers/kubernetes/inventory/persister/definitions/container_collections.rb
  spec/models/manageiq/providers/kubernetes/container_manager/refresher_spec.rb
Labels: enhancement

#532 Clarify that KubeVirt is OSV
  app/models/manageiq/providers/kubernetes/container_manager.rb
Labels: enhancement, radjabov/yes?
