Repository ManageIQ/manageiq-providers-kubernetes, pull requests merged in 2024-03, with the labels that each got.

#521 Update codeclimate channel to the latest in manageiq-style
  .codeclimate.yml
Labels: dependencies

#518 Delete Prometheus Alerts MonitoringManager
  app/models/manageiq/providers/kubernetes/container_manager.rb
  app/models/manageiq/providers/kubernetes/monitoring_manager.rb
  app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher.rb
  app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner.rb
  app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin.rb
  app/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/stream.rb
  config/settings.yml
  manageiq-providers-kubernetes.gemspec
  spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
  spec/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/runner_mixin_spec.rb
  spec/models/manageiq/providers/kubernetes/monitoring_manager/event_catcher/stream_spec.rb
  spec/models/manageiq/providers/kubernetes/monitoring_manager_spec.rb
  systemd/manageiq-providers-kubernetes_monitoring_manager_event_catcher.target
  systemd/manageiq-providers-kubernetes_monitoring_manager_event_catcher@.service
Labels: technical debt, dependencies

#522 Fix prometheus http_proxy using 0.0.0.0:80
  app/models/manageiq/providers/kubernetes/container_manager.rb
  app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/prometheus_client_mixin.rb
Labels: bug, radjabov/yes

#523 Add specs covering K8s `.verify_credentials`
  spec/models/manageiq/providers/kubernetes/container_manager_spec.rb
Labels: test
